#!/bin/bash
# Final upgrade command after import order fix

echo "====================================================================="
echo "CRITICAL FIX APPLIED: Model Import Order Corrected"
echo "====================================================================="
echo ""
echo "✅ vendor_category_document_line is now imported BEFORE vendor_category"
echo "✅ Security access for base.group_user exists"
echo "✅ Python cache cleared"
echo ""
echo "====================================================================="
echo "UPGRADE COMMANDS"
echo "====================================================================="
echo ""
echo "Run these commands IN ORDER:"
echo ""
echo "1. Stop Odoo:"
echo "   sudo systemctl stop odoo"
echo ""
echo "2. Upgrade module:"
echo "   cd /home/prasanna/dev/odoo"
echo "   ./odoo-bin -c odoo.conf -u vendor_management -d vendor_management --stop-after-init"
echo ""
echo "3. Start Odoo:"
echo "   sudo systemctl start odoo"
echo ""
echo "====================================================================="
echo "WHAT WAS FIXED"
echo "====================================================================="
echo ""
echo "BEFORE (WRONG):"
echo "  from . import vendor_category"
echo "  from . import vendor_category_document_line  # Too late!"
echo ""
echo "AFTER (CORRECT):"
echo "  from . import vendor_category_document_line  # First!"
echo "  from . import vendor_category  # Now can reference it"
echo ""
echo "====================================================================="
