[options]
admin_passwd = $pbkdf2-sha512$600000$p5RS6v0/B2DsXcs5p7RWag$dDTz.ie7RqoJa5Dw0K1LkXpoOX59NzMv4Sk5htdiXeeNdiWM4lcpJEt03YmHT/P3couvXMNUWoBcFdK3474Ckw
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = admin
addons_path = /home/fnetadmin/asset_management/new_project,/home/fnetadmin/asset_management/addons,/home/fnetadmin/asset_management/odoo/addons
http_port = 8169
xmlrpc_port = 8169
max_cron_threads = 1
limit_time_cpu = 3600
limit_time_real = 7200
limit_memory_soft = 4294967296
limit_memory_hard = 5368709120
log_level = info
logfile = /home/fnetadmin/asset_management/new_project.log
db_name = new_project
list_db = True

