[options]
admin_passwd = $pbkdf2-sha512$600000$wrg3ZszZ27t3LiUkpDSGMA$IL7z50YJODW14fhV1fDECwp5Ia.9Wdp9CrAIzfAjBU4wiPIsqHMQYkL.qh6toOltvyHSc9eBgjuAECYhs3Y8Kg
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = admin
addons_path = /home/fnetadmin/odoo19/addons,/home/fnetadmin/odoo19/odoo/addons,/home/fnetadmin/odoo19/asset_addons/
http_port = 9069
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
db_name = odoo19

