[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = admin
addons_path = /home/fnetadmin/asset_management/addons,/home/fnetadmin/asset_management/odoo/addons,/home/fnetadmin/asset_management/asset_addons_dev
http_port = 8079
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
# db_name = asset_new
