[options]
admin_passwd = $pbkdf2-sha512$600000$jTFmzBnDuDcGgHCO8T6ntA$toeWNf/LyDGu0KyS225d3p5JM2Ok8TtMcIgZ4/gG762CDbB87MjrcEJLbL3xXAXZFMujmc8ubHx4jNOcGKHkMg
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = admin
addons_path = /home/fnetadmin/odoo19/addons,/home/fnetadmin/odoo19/odoo/addons,/home/fnetadmin/odoo19/asset_addons_dev/
http_port = 8069
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
db_name = asset_new

